// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Perakaravan.Data.Context;

#nullable disable

namespace Perakaravan.Data.Migrations
{
    [DbContext(typeof(PeraContext))]
    partial class PeraContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Perakaravan.Domain.Entities.LoginUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedTime")
                        .HasColumnOrder(32);

                    b.Property<string>("CreatedUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CreatedUser")
                        .HasColumnOrder(30);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("Email")
                        .HasColumnOrder(6);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Name")
                        .HasColumnOrder(2);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("Password")
                        .HasColumnOrder(5);

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Phone")
                        .HasColumnOrder(7);

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("RefreshToken")
                        .HasColumnOrder(8);

                    b.Property<DateTime?>("RefreshTokenExpire")
                        .HasColumnType("datetime2")
                        .HasColumnName("RefreshTokenExpire")
                        .HasColumnOrder(9);

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Surname")
                        .HasColumnOrder(3);

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedTime")
                        .HasColumnOrder(33);

                    b.Property<string>("UpdatedUser")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UpdatedUser")
                        .HasColumnOrder(31);

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Username")
                        .HasColumnOrder(4);

                    b.HasKey("Id");

                    b.ToTable("LoginUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedTime = new DateTime(2024, 2, 18, 21, 2, 12, 621, DateTimeKind.Unspecified).AddTicks(3686),
                            CreatedUser = "admin",
                            Email = "6i1RRb8yv2k93LY76uQYXg==",
                            IsDeleted = false,
                            Name = "İsmet Aydın",
                            Password = "oscldUV7cgbn0b8V8HmpyQ==",
                            Phone = "YCPrDtNs284S9G5ikUK4fA==",
                            Surname = "YURTSEVER",
                            Username = "isayyu"
                        },
                        new
                        {
                            Id = 2,
                            CreatedTime = new DateTime(2024, 2, 18, 21, 2, 12, 621, DateTimeKind.Unspecified).AddTicks(3729),
                            CreatedUser = "admin",
                            Email = "YPRqARSJPWq8wMRbcsaVck2Wnq3lgHLvl0z7T+wsoKc=",
                            IsDeleted = false,
                            Name = "Halil İbrahim",
                            Password = "PaFmrqp5h+CAYfGVZvjZsw==",
                            Phone = "YCPrDtNs284S9G5ikUK4fA==",
                            Surname = "ARAÇ",
                            Username = "ibrahim"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
